### ISSUE TITLE
Troubleshoot error message

### ISSUE THREAD

**Issue by vsnt** [w3c-ccg/meetings#39]
Heather is too tired to address this now, but trouble shoot error message for minutes for solid extra meeting and the regular meeting on 3-10. https://github.com/w3c-ccg/meetings/actions/runs/640488484

**Comment by rhiaro** [comment]
I think it's because the irc log in solidextra was deleted and reuploaded *after* the html was already generated. If you delete the html file at the same time as you are deleting the irc log, then it should regenerate it. I *think*. (Were you deleting and reuploading because of edits to the files?)

The 3-10 regular meeting minutes didn't get generated because the irc log needs to be called `irc.log`, or the github action doesn't run at all.

**Comment by vsnt** [comment]
Ah, I should know better than to simultaneously batch process minutes... I removed the .txt on the regular mtg.

And yes, I should have likely just deleted all the generated files in solidextra. I guess I could do that now and reupload the log and audio.

**Comment by rhiaro** [comment]
This is fixed. General rule is if you need to mess with the raw irc log, delete the autogenerated files (email.log and index.html) *first* because changes (deletion/edit/re-adding) to the irc log trigger all the scripts which then get confused if the email and index files are already present.
